core/urls.py
# -*- Mode: Python; coding: utf-8 -*-
from django.conf.urls import *
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    pedido
)

app_name = 'core'

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^checkout/$', CheckoutView.as_view(), name='checkout'),
    url(r'^resumo-do-pedido/$', OrderSummaryView.as_view(), name='order-summary'),
    url(r'^produto/(?P<slug>[\w-]+)/$', ItemDetailView.as_view(), name='product'),
    url(r'^add-to-cart/(?P<slug>[\w-]+)/$', add_to_cart, name='add-to-cart'),
    url(r'^add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    url(r'^remove-from-cart/(?P<slug>[\w-]+)/$', remove_from_cart, name='remove-from-cart'),
    url(r'^remove-item-from-cart/(?P<slug>[\w-]+)/$', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    url(r'^pagamento/(?P<payment_option>[-\w]+)/$', PaymentView.as_view(), name='payment'),
    url(r'^request-refund/$', RequestRefundView.as_view(), name='request-refund'),
    url(r'^pedido/(?P<id>[-\w]+)/$',pedido, name="pedido"),
]

pizza/urls.py
# -*- Mode: Python; coding: utf-8 -*-
from django.contrib.auth.decorators import permission_required
from django.conf.urls import *
from django.contrib import admin
from pizza.views import *
from django.contrib.staticfiles import views
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from django.conf import settings
from . import views
# from django.contrib.auth.views import login
from django.contrib.auth import views as auth_views

from rest_framework.urlpatterns import format_suffix_patterns

urlpatterns = [
    # Inicio

    # Fim Inicio
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('core.urls', namespace='core')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

urlpatterns = format_suffix_patterns(urlpatterns)

core/models.py
# -*- Mode: Python; coding: utf-8 -*-
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
import os
from datetime import datetime
# import sys
# reload(sys)
# sys.setdefaultencoding('utf8')


CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username)


class Tamanho(models.Model):
    nome = models.CharField(u'Tamanho', max_length=40)

    def __unicode__(self):
        return self.nome

    class Meta:
        verbose_name = u'Tamanho'
        verbose_name_plural = u'TAMANHOS'


class Categoria(models.Model):
    id = models.AutoField(primary_key=True)
    nome = models.CharField(u'Categoria', max_length=100)
    slug = models.SlugField()
    active = models.CharField(u'Active', blank=True, max_length=10)

    def __unicode__(self):
        return self.nome

    class Meta:
        verbose_name = u'Uma Categoria'
        verbose_name_plural = u'CATEGORIAS'
        ordering = ['id']


class Adicional(models.Model):
    adicional_nome = models.CharField(max_length=255, blank=True, null=True)

    def __unicode__(self):
        return self.adicional_nome


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.DecimalField(u'Valor', max_digits=8, decimal_places=2)
    discount_price = models.DecimalField(
        blank=True, null=True, max_digits=8, decimal_places=2)
    ativacao = models.BooleanField(u'Ativar/Desativar', default=True)
    slug = models.SlugField(null=True, default=None, max_length=300,
                            unique=True, db_index=True)
    description = RichTextUploadingField(u'Descrição', blank=True)
    image = models.ImageField(blank=True, null=True,
                              upload_to='uploaded_images')
    tamanho = models.ForeignKey(Tamanho, on_delete=models.CASCADE)
    produtos = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    #adicional = models.ForeignKey(Adicional, on_delete=models.CASCADE, blank=True, null=True)
    picked = models.ManyToManyField(
        Adicional, blank=True, related_name='add_adicional')

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })

    class Meta:
        verbose_name = u'Um item'
        verbose_name_plural = u'ITEM'


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return "({0},{1})".format(self.quantity, self.item.title)

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()

    class Meta:
        verbose_name = u'Um item de Pedido'
        verbose_name_plural = u'ITEM DE PEDIDO'


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(
        u'Código de referência', max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(u'Em Processo', default=False)
    being_delivered = models.BooleanField(u'Saiu para Entrega', default=False)
    received = models.BooleanField(u'Entregue', default=False)
    refund_granted = models.BooleanField(u'Pagamento Efetuado', default=False)
    refund_requested = models.BooleanField(
        u'Pagamento Cancelado', default=False)

    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', related_name='billing_pagamento', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return str(self.user.username)

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total

    class Meta:
        verbose_name = u'Um Encomendas'
        verbose_name_plural = u'ENCOMENDAS'


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = u'Um Endereço'
        verbose_name_plural = u'ENDEREÇO'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user.username)

    class Meta:
        verbose_name = u'Um Pagamento'
        verbose_name_plural = u'PAGAMENTO'


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return str(self.code)

    class Meta:
        verbose_name = u'Um Cupom'
        verbose_name_plural = u'CUPOM'


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = u'Um Reembolso'
        verbose_name_plural = u'REEMBOLSO'


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base.filter.html
<div class="section-tabs section-products">
                  <h2 class="section-title">PROMOÇÃO DO DIA</h2>
                  <ul class="nav nav-tabs pizzaro-nav-tabs" >
                     {% for itens in base_filter %}
                     <li class="nav-item {{itens.active}}">
                        <a href="#{{itens.slug}}" data-toggle="tab">{{itens.nome}}</a>
                     </li>
                     {% endfor %}
                  </ul>
                  <div class="tab-content">
                       {% for itens in base_filter %}
                     <div class="tab-pane {{itens.active}}" id="{{itens.slug}}">
                        <div class="section-products">
                           <div class="woocommerce columns-4">
                              <div class="columns-4">
                                 <ul class="products">
                                      {% for obj in itens.item_set.all %}
                                    <li class="product">
                                       <div class="product-outer">
                                          <div class="product-inner">
                                             <div class="product-image-wrapper">
                                                <a href="#" class="woocommerce-LoopProduct-link">
                                                <img src="{{ obj.image.url }}" class="img-responsive" alt="">
                                                </a>
                                             </div>
                                             <div class="product-content-wrapper">
                                                <a href="{{ obj.get_absolute_url }}" class="woocommerce-LoopProduct-link">
                                                   <h3>{{ obj.title }}</h3>
                                                   <div itemprop="description">
                                                      <p style="max-height: none;">{{obj.description|safe}}</p>
                                                   </div>
                                                   <div class="yith_wapo_groups_container">
                                                      <div class="ywapo_group_container ywapo_group_container_radio form-row form-row-wide " data-requested="1" data-type="radio" data-id="1" data-condition="">
                                                         <h3><span>TAMANHO</span></h3>
                                                         <div class="ywapo_input_container ywapo_input_container_radio">


                                                            <span class="ywapo_label_tag_position_after"><span class="ywapo_option_label ywapo_label_position_after">{{obj.tamanho.nome}}</span></span><span class="ywapo_label_price"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">R$</span>{{ obj.price|stringformat:"d" }}<span class="woocommerce-Price-currencySymbol">,00</span></span></span>
                                                         </div>
                                                      </div>
                                                   </div>
                                                </a>
                                                <div class="hover-area">
                                                   <a rel="nofollow" href="{{ obj.get_absolute_url }}" class="button product_type_simple add_to_cart_button ajax_add_to_cart">EU QUERO!</a>
                                                </div>
                                             </div>
                                          </div>
                                       </div>
                                    </li>
                                     {% endfor %}
                                 </ul>
                              </div>
                           </div>
                        </div>
                     </div>
                     {% endfor %}
                  </div>
               </div>

templates/base.html
{% load staticfiles %}{% load i18n %}<!DOCTYPE html>
<html lang="pt-br">
<head>
<title>TARANTELLA PIZZA & BURGUER | SITE OFICIAL</title>
<meta charset="UTF-8" />
<!-- Ta xeretando nosso código né? Pelo jeito você é um desenvolvedor Front-end e/ou Back-end.
Entre em contado conosco e envie no e-mail o código INSINUANTE para novas oportunidades -->
<meta name="description" content="TARANTELLA PIZZA & BURGUER | SITE OFICIAL"/>
<meta name="keywords" content="pizza" />
<meta name="author" content="Sancley Alhadef">
<meta name="Empresa" content="Wings Design - www.wingsdesign.com.br">
<meta name="Email" content="contato@wingsdesign.com.br">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Css -->
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" media="all" />
<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}" media="all" />
<link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}" media="all" />
<link rel="stylesheet" type="text/css" href="{% static 'css/font-pizzaro.css' %}" media="all" />
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" media="all" />
<link rel="stylesheet" type="text/css" href="{% static 'css/red.css' %}" media="all" />
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}" media="all" />
<!--  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css">-->
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CYanone+Kaffeesatz:200,300,400,700" rel="stylesheet">
<link rel="shortcut icon" href="{% static 'images/fav-icon.png' %}">
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <!-- Favicon and touch icons -->
<link rel="shortcut icon" href="{% static 'images/favicon/favicon.ico' %}">
{% block css %}{% endblock %}
</head>
<body class="page-template-template-homepage-v1 home-v1 single-product">{% block base %}{% endblock %}
<!-- Javascript -->
<script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/tether.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/social.share.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/scripts.min.js' %}"></script>
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}{% load staticfiles %}{% block base %}

               <!-- AQUI MODEL FILTER -->
               <div class="section-products">
                  <h2 class="section-title">FAÇA AGORA MESMO SEU PEDIDO</h2>
                  <div class="columns-4">
                     <ul class="products">
                        {% for item in base_filter_item %}
                        <li class="product">
                           <div class="product-outer">
                              <div class="product-inner">
                                 <div class="product-image-wrapper">
                                    <a href="{{ item.get_absolute_url }}" class="woocommerce-LoopProduct-link">
                                    <img src="{{ item.image.url }}" class="img-responsive" alt="">
                                    </a>
                                 </div>
                                 <div class="product-content-wrapper">
                                    <a href="{{ item.get_absolute_url }}" class="woocommerce-LoopProduct-link">
                                       <h3>{{ item.title|upper }}</h3>
                                       <div itemprop="description">
                                          <p style="max-height: none;">{{item.description|safe}}</p>
                                       </div>
                                       <div class="yith_wapo_groups_container">
                                          <div class="ywapo_group_container ywapo_group_container_radio form-row form-row-wide " data-requested="1" data-type="radio" data-id="1" data-condition="">
                                             <h3><span>TAMANHO</span></h3>
                                             <div class="ywapo_input_container ywapo_input_container_radio">


                                                <span class="ywapo_label_tag_position_after"><span class="ywapo_option_label ywapo_label_position_after">{{item.tamanho.nome}}</span></span><span class="ywapo_label_price"><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">R$</span>{{ item.price }}<span class="woocommerce-Price-currencySymbol"></span></span></span>
                                             </div> 
                                          </div>
                                       </div>
                                    </a>
                                    <div class="hover-area">
                                       <a rel="nofollow" href="{{ item.get_absolute_url }}" class="button product_type_simple add_to_cart_button ajax_add_to_cart">EU QUERO!</a>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </li>
                        {% endfor %}
                     </ul>
                  </div>
               </div>
               
{% endblock %}

templates/order_summary.html
{% extends "base.html" %}{% load staticfiles %}{% block base %}
<div class="containter">
<div class="col-md-10">
                     <div id="post-8" class="post-8 page type-page status-publish hentry">
                        <div class="entry-content">
                           <div class="woocommerce">
                             
                                 <table class="shop_table shop_table_responsive cart" >
                                    <thead>
                                       <tr>
                                          <th class="product-remove">&nbsp;</th>
                                          <th class="product-thumbnail">&nbsp;</th>
                                          <th class="product-name">PRODUTO</th>
                                          <th class="product-price">VALOR</th>
                                          <th class="product-quantity">QUANTIDADE</th>
                                          <th class="product-subtotal">TOTAL</th>
                                       </tr>
                                    </thead>
                                    <tbody>
                                      {% for order_item in object.items.all %}
                                       <tr class="cart_item">
                                          <td class="product-remove">
                                             <a href="{% url 'core:remove-from-cart' order_item.item.slug %}" class="remove" >&times;</a>
                                          </td>
                                          <td class="product-thumbnail">
                                             <a href="#">
                                             <img width="180" height="180" src="{{ order_item.item.image.url }}" alt=""/>
                                             </a>
                                          </td>
                                          <td class="product-name" data-title="PRODUTO">
                                             <a href="#">{{ order_item.item.title }}</a>
                                             <dl class="variation">
                                                <dt class="variation-Baseprice">TAMANHO:</dt>
                                                {{order_item.item.tamanho.nome|upper}} 
                                                
                                                <dd class="variation-PickSizespanclasswoocommerce-Price-amountamountspanclasswoocommerce-Price-currencySymbol36span2590span">
                                                  
                                                  <p>
                                                   <strong>Adicionais: </strong>
                                                   {% for itens in order_item.item.picked.all %}     
                                                    {{itens.adicional_nome }},
                                                   
                                                   {% endfor %}

                                                    </p>
                                                </dd>

                                             </dl>

                                          </td>
                                          <td class="product-price" data-title="VALOR">
                                             <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#36;</span>{{ order_item.item.price }}</span>
                                          </td>
                                          <td class="product-quantity" data-title="QUANTIDADE">
                                             <div class="qty-btn">
                                                <label>Quatidade</label>
                                                <div class="quantity">
                                                   <a href="{% url 'core:remove-single-item-from-cart' order_item.item.slug %}"><i class="fa fa-minus mr-2"></i></a>
                                                    {{ order_item.quantity }}
                                                    <a href="{% url 'core:add-to-cart' order_item.item.slug %}"><i class="fa fa-plus ml-2"></i></a>
                                                </div>
                                             </div>
                                          </td>
                                          <td class="product-subtotal" data-title="TOTAL">
                                             <span class="woocommerce-Price-amount amount">
                                               {% if order_item.item.discount_price %}
                                              <span class="woocommerce-Price-currencySymbol">R$</span>{{ order_item.get_total_discount_item_price }} </span><span class="badge badge-primary"> Desconto de R${{ order_item.get_amount_saved }}</span>
                                               {% else %}
                                                  R${{ order_item.get_total_item_price }}
                                              {% endif %}
                                          </td>
                                       </tr>
                                        {% endfor %}
                                        <tr>
                                          <td colspan="6" class="actions">
                                             <div class="coupon">
                                                <label for="coupon_code">Cupom:</label>
                                                <input type="text" name="coupon_code" class="input-text" id="coupon_code" value="" placeholder="Código do Cupom" />
                                                <input type="submit" class="button" name="apply_coupon" value="Aplicar Cupom" />
                                             </div>
                                             
                                                <input onclick="window.location.href = '/';" type="submit" class="button" name="update_cart" value="CONTÍNUAR COMPRANDO" />
                                             
                                             <div class="wc-proceed-to-checkout">
                                                <a href="/checkout/" class="checkout-button button alt wc-forward">FINALIZAR PEDIDO</a>
                                             </div>
                                             <input type="hidden" id="_wpnonce" name="_wpnonce" value="21ca9d92f8" /><input type="hidden" name="_wp_http_referer"  />
                                          </td>
                                       </tr>
                                    </tbody>
                                 </table>
                              
                              <div class="cart-collaterals">
                                 <div class="cart_totals ">
                                    <h2>Cart Totals</h2>
                                    <table  class="shop_table shop_table_responsive">
                                       <tr class="cart-subtotal">
                                          <th>Cupom</th>
                                          <td data-title="Subtotal">
                                             <span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">R$</span>{{ object.coupon.amount }}</span>
                                          </td>
                                       </tr>
                                       <tr class="order-total">
                                          <th>Total</th>
                                          <td data-title="Total">
                                             <strong><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">R$</span>{{ object.get_total }}</span></strong>
                                          </td>
                                       </tr>
                                    </table>
                                    <div class="wc-proceed-to-checkout">
                                       <a href="/checkout/" class="checkout-button button alt wc-forward">FAZER PEDIDO</a>
                                    </div>
                                 </div>
                              </div>
                           </div>
                        </div>
                     </div>
                     <!-- .entry-content -->
                    </main><!-- #main -->
               </div>
               <!-- #post-## -->
            </div>
            <!-- #primary -->
         </div>
         <!-- .col-full -->
      </div>
</div>
</div>
{% endblock %}

templates/request_adicional.html
{% block content %}
  <main>
    <div class="container">

    <h2>Request Refund</h2>
    <form method="POST">
        {% csrf_token %}
        {{ form }}
        <button type='submit' class='btn btn-primary'>Submit</button>
    </form>

    </div>
  </main>

{% endblock content %}